# Generated by Django 3.2.3 on 2021-05-20 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pytube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_changed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'PyTube Switch',
            },
        ),
        migrations.CreateModel(
            name='YoutubeDL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_changed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'YouTube-DL Switch',
            },
        ),
    ]
